# ============================================================================
# GET USER BY AUTH ID
# ============================================================================

query GetUserByAuthId($id: String!) @auth(level: USER) {
  user(id: $id) {
    id
    businessId
    role
    firstName
    lastName
    email
    phone
    isActive
  }
}
