// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrFr8RBMIkvSgVDBuzi8NaAWakx_CxFCg',
    appId: '1:795893319163:web:fb9c46771fbef2ab55775e',
    messagingSenderId: '795893319163',
    projectId: 'ikpharma-dev',
    authDomain: 'ikpharma-dev.firebaseapp.com',
    storageBucket: 'ikpharma-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwA_aT2E0fnpeePvbgocN6DOFBQ69WMcg',
    appId: '1:795893319163:android:cddc38fe3982c75655775e',
    messagingSenderId: '795893319163',
    projectId: 'ikpharma-dev',
    storageBucket: 'ikpharma-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSGH7E6PHI8Xy3h6mkiEeY12N8u-8BKsI',
    appId: '1:795893319163:ios:545db9f3274f3f8f55775e',
    messagingSenderId: '795893319163',
    projectId: 'ikpharma-dev',
    storageBucket: 'ikpharma-dev.firebasestorage.app',
    iosBundleId: 'com.example.ikPharma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSGH7E6PHI8Xy3h6mkiEeY12N8u-8BKsI',
    appId: '1:795893319163:ios:545db9f3274f3f8f55775e',
    messagingSenderId: '795893319163',
    projectId: 'ikpharma-dev',
    storageBucket: 'ikpharma-dev.firebasestorage.app',
    iosBundleId: 'com.example.ikPharma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrFr8RBMIkvSgVDBuzi8NaAWakx_CxFCg',
    appId: '1:795893319163:web:944a50818aefe7cf55775e',
    messagingSenderId: '795893319163',
    projectId: 'ikpharma-dev',
    authDomain: 'ikpharma-dev.firebaseapp.com',
    storageBucket: 'ikpharma-dev.firebasestorage.app',
  );
}
