extend type Customer {
  """
  ✨ Implicit foreign key field based on `Customer`.`address`. It must match the value of `Address`.`id`. See `@ref` for how to customize it.
  """
  addressId: UUID @fdc_generated(from: "Customer.address", purpose: IMPLICIT_REF_FIELD)
}
extend type Employee {
  """
  ✨ Implicit foreign key field based on `Employee`.`address`. It must match the value of `Address`.`id`. See `@ref` for how to customize it.
  """
  addressId: UUID @fdc_generated(from: "Employee.address", purpose: IMPLICIT_REF_FIELD)
}
extend type Location {
  """
  ✨ Implicit foreign key field based on `Location`.`address`. It must match the value of `Address`.`id`. See `@ref` for how to customize it.
  """
  addressId: UUID @fdc_generated(from: "Location.address", purpose: IMPLICIT_REF_FIELD)
}
extend type Product {
  """
  ✨ Implicit foreign key field based on `Product`.`createdBy`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  createdById: String! @fdc_generated(from: "Product.createdBy", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Product`.`manufacturer`. It must match the value of `Manufacturer`.`id`. See `@ref` for how to customize it.
  """
  manufacturerId: UUID! @fdc_generated(from: "Product.manufacturer", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Product`.`primarySupplier`. It must match the value of `Supplier`.`id`. See `@ref` for how to customize it.
  """
  primarySupplierId: UUID! @fdc_generated(from: "Product.primarySupplier", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Product`.`therapeuticClass`. It must match the value of `TherapeuticClass`.`id`. See `@ref` for how to customize it.
  """
  therapeuticClassId: UUID! @fdc_generated(from: "Product.therapeuticClass", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Product`.`therapeuticSubclass`. It must match the value of `TherapeuticSubclass`.`id`. See `@ref` for how to customize it.
  """
  therapeuticSubclassId: UUID @fdc_generated(from: "Product.therapeuticSubclass", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Product`.`updatedBy`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  updatedById: String! @fdc_generated(from: "Product.updatedBy", purpose: IMPLICIT_REF_FIELD)
}
extend type ProductBatch {
  """
  ✨ Implicit foreign key field based on `ProductBatch`.`createdBy`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  createdById: String! @fdc_generated(from: "ProductBatch.createdBy", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `ProductBatch`.`updatedBy`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  updatedById: String! @fdc_generated(from: "ProductBatch.updatedBy", purpose: IMPLICIT_REF_FIELD)
}
extend type SeasonalPattern {
  """
  ✨ Implicit foreign key field based on `SeasonalPattern`.`learnedFrom`. It must match the value of `DateRange`.`id`. See `@ref` for how to customize it.
  """
  learnedFromId: UUID! @fdc_generated(from: "SeasonalPattern.learnedFrom", purpose: IMPLICIT_REF_FIELD)
}
extend type Supplier {
  """
  ✨ Implicit foreign key field based on `Supplier`.`address`. It must match the value of `Address`.`id`. See `@ref` for how to customize it.
  """
  addressId: UUID @fdc_generated(from: "Supplier.address", purpose: IMPLICIT_REF_FIELD)
}
extend type SupplierPerformanceScore {
  """
  ✨ Implicit foreign key field based on `SupplierPerformanceScore`.`calculatedFor`. It must match the value of `DateRange`.`id`. See `@ref` for how to customize it.
  """
  calculatedForId: UUID! @fdc_generated(from: "SupplierPerformanceScore.calculatedFor", purpose: IMPLICIT_REF_FIELD)
}
