extend type Query {
  """
  ✨ Look up a single `ActiveIngredient` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  activeIngredient(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ActiveIngredient_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ActiveIngredient_FirstRow
  ): ActiveIngredient @fdc_generated(from: "ActiveIngredient", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Address` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  address(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Address_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Address_FirstRow
  ): Address @fdc_generated(from: "Address", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Attendance` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  attendance(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Attendance_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Attendance_FirstRow
  ): Attendance @fdc_generated(from: "Attendance", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `BulkPackaging` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  bulkPackaging(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: BulkPackaging_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: BulkPackaging_FirstRow
  ): BulkPackaging @fdc_generated(from: "BulkPackaging", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Business` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  business(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Business_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Business_FirstRow
  ): Business @fdc_generated(from: "Business", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Conversation` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  conversation(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Conversation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Conversation_FirstRow
  ): Conversation @fdc_generated(from: "Conversation", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Customer` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  customer(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Customer_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Customer_FirstRow
  ): Customer @fdc_generated(from: "Customer", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `DateRange` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  dateRange(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DateRange_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DateRange_FirstRow
  ): DateRange @fdc_generated(from: "DateRange", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Dimensions` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  dimensions(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Dimensions_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Dimensions_FirstRow
  ): Dimensions @fdc_generated(from: "Dimensions", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `DrugInteraction` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  drugInteraction(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DrugInteraction_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DrugInteraction_FirstRow
  ): DrugInteraction @fdc_generated(from: "DrugInteraction", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Employee` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  employee(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Employee_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Employee_FirstRow
  ): Employee @fdc_generated(from: "Employee", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ExpiryWarningThresholds` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  expiryWarningThresholds(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ExpiryWarningThresholds_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ExpiryWarningThresholds_FirstRow
  ): ExpiryWarningThresholds @fdc_generated(from: "ExpiryWarningThresholds", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `FinancialRecord` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  financialRecord(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: FinancialRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FinancialRecord_FirstRow
  ): FinancialRecord @fdc_generated(from: "FinancialRecord", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `FormularyStatus` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  formularyStatus(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: FormularyStatus_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FormularyStatus_FirstRow
  ): FormularyStatus @fdc_generated(from: "FormularyStatus", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `GoodsReceipt` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  goodsReceipt(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GoodsReceipt_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GoodsReceipt_FirstRow
  ): GoodsReceipt @fdc_generated(from: "GoodsReceipt", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `InsuranceReimbursement` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  insuranceReimbursement(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: InsuranceReimbursement_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: InsuranceReimbursement_FirstRow
  ): InsuranceReimbursement @fdc_generated(from: "InsuranceReimbursement", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `InventoryLevel` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  inventoryLevel(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: InventoryLevel_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: InventoryLevel_FirstRow
  ): InventoryLevel @fdc_generated(from: "InventoryLevel", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Invoice` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  invoice(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Invoice_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Invoice_FirstRow
  ): Invoice @fdc_generated(from: "Invoice", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Location` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  location(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Location_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Location_FirstRow
  ): Location @fdc_generated(from: "Location", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Manufacturer` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  manufacturer(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Manufacturer_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Manufacturer_FirstRow
  ): Manufacturer @fdc_generated(from: "Manufacturer", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Message` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  message(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Message_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Message_FirstRow
  ): Message @fdc_generated(from: "Message", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `MessageAttachment` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  messageAttachment(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MessageAttachment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MessageAttachment_FirstRow
  ): MessageAttachment @fdc_generated(from: "MessageAttachment", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `MessageReadReceipt` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  messageReadReceipt(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MessageReadReceipt_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MessageReadReceipt_FirstRow
  ): MessageReadReceipt @fdc_generated(from: "MessageReadReceipt", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Payment` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  payment(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Payment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Payment_FirstRow
  ): Payment @fdc_generated(from: "Payment", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Payroll` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  payroll(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Payroll_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Payroll_FirstRow
  ): Payroll @fdc_generated(from: "Payroll", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Product` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  product(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Product_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Product_FirstRow
  ): Product @fdc_generated(from: "Product", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ProductBatch` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  productBatch(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ProductBatch_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProductBatch_FirstRow
  ): ProductBatch @fdc_generated(from: "ProductBatch", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ProductPricing` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  productPricing(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ProductPricing_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProductPricing_FirstRow
  ): ProductPricing @fdc_generated(from: "ProductPricing", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ProductSupplier` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  productSupplier(
    """
    The key used to identify the object.
    """
    key: ProductSupplier_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProductSupplier_FirstRow
  ): ProductSupplier @fdc_generated(from: "ProductSupplier", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PromotionalDiscount` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  promotionalDiscount(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PromotionalDiscount_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PromotionalDiscount_FirstRow
  ): PromotionalDiscount @fdc_generated(from: "PromotionalDiscount", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PurchaseOrder` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  purchaseOrder(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PurchaseOrder_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PurchaseOrder_FirstRow
  ): PurchaseOrder @fdc_generated(from: "PurchaseOrder", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PurchaseOrderLineItem` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  purchaseOrderLineItem(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PurchaseOrderLineItem_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PurchaseOrderLineItem_FirstRow
  ): PurchaseOrderLineItem @fdc_generated(from: "PurchaseOrderLineItem", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PurchaseRequisition` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  purchaseRequisition(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PurchaseRequisition_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PurchaseRequisition_FirstRow
  ): PurchaseRequisition @fdc_generated(from: "PurchaseRequisition", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `RecallDetails` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  recallDetails(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: RecallDetails_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: RecallDetails_FirstRow
  ): RecallDetails @fdc_generated(from: "RecallDetails", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ReorderSuggestion` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  reorderSuggestion(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ReorderSuggestion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ReorderSuggestion_FirstRow
  ): ReorderSuggestion @fdc_generated(from: "ReorderSuggestion", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `SalesLineItem` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  salesLineItem(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SalesLineItem_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SalesLineItem_FirstRow
  ): SalesLineItem @fdc_generated(from: "SalesLineItem", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `SalesTransaction` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  salesTransaction(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SalesTransaction_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SalesTransaction_FirstRow
  ): SalesTransaction @fdc_generated(from: "SalesTransaction", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `SeasonalPattern` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  seasonalPattern(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SeasonalPattern_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SeasonalPattern_FirstRow
  ): SeasonalPattern @fdc_generated(from: "SeasonalPattern", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Shift` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  shift(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Shift_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Shift_FirstRow
  ): Shift @fdc_generated(from: "Shift", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `StorageLocation` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  storageLocation(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: StorageLocation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StorageLocation_FirstRow
  ): StorageLocation @fdc_generated(from: "StorageLocation", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `SubstitutionRules` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  substitutionRules(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SubstitutionRules_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SubstitutionRules_FirstRow
  ): SubstitutionRules @fdc_generated(from: "SubstitutionRules", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Supplier` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  supplier(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Supplier_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Supplier_FirstRow
  ): Supplier @fdc_generated(from: "Supplier", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `SupplierPerformanceScore` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  supplierPerformanceScore(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SupplierPerformanceScore_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SupplierPerformanceScore_FirstRow
  ): SupplierPerformanceScore @fdc_generated(from: "SupplierPerformanceScore", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `TemperatureRange` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  temperatureRange(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TemperatureRange_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TemperatureRange_FirstRow
  ): TemperatureRange @fdc_generated(from: "TemperatureRange", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `TemperatureReading` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  temperatureReading(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TemperatureReading_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TemperatureReading_FirstRow
  ): TemperatureReading @fdc_generated(from: "TemperatureReading", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `TherapeuticClass` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  therapeuticClass(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TherapeuticClass_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TherapeuticClass_FirstRow
  ): TherapeuticClass @fdc_generated(from: "TherapeuticClass", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `TherapeuticSubclass` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  therapeuticSubclass(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TherapeuticSubclass_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TherapeuticSubclass_FirstRow
  ): TherapeuticSubclass @fdc_generated(from: "TherapeuticSubclass", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `VolumeDiscount` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  volumeDiscount(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: VolumeDiscount_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: VolumeDiscount_FirstRow
  ): VolumeDiscount @fdc_generated(from: "VolumeDiscount", purpose: QUERY_SINGLE)
  """
  ✨ List `ActiveIngredient` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  activeIngredients(
    """
    Filter condition to narrow down the query results.
    """
    where: ActiveIngredient_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ActiveIngredient_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ActiveIngredient_Having
  ): [ActiveIngredient!]! @fdc_generated(from: "ActiveIngredient", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Address` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  addresses(
    """
    Filter condition to narrow down the query results.
    """
    where: Address_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Address_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Address_Having
  ): [Address!]! @fdc_generated(from: "Address", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Attendance` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  attendances(
    """
    Filter condition to narrow down the query results.
    """
    where: Attendance_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Attendance_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Attendance_Having
  ): [Attendance!]! @fdc_generated(from: "Attendance", purpose: QUERY_MULTIPLE)
  """
  ✨ List `BulkPackaging` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  bulkPackagings(
    """
    Filter condition to narrow down the query results.
    """
    where: BulkPackaging_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [BulkPackaging_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: BulkPackaging_Having
  ): [BulkPackaging!]! @fdc_generated(from: "BulkPackaging", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Business` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  businesses(
    """
    Filter condition to narrow down the query results.
    """
    where: Business_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Business_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Business_Having
  ): [Business!]! @fdc_generated(from: "Business", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Conversation` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  conversations(
    """
    Filter condition to narrow down the query results.
    """
    where: Conversation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Conversation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Conversation_Having
  ): [Conversation!]! @fdc_generated(from: "Conversation", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Customer` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  customers(
    """
    Filter condition to narrow down the query results.
    """
    where: Customer_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Customer_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Customer_Having
  ): [Customer!]! @fdc_generated(from: "Customer", purpose: QUERY_MULTIPLE)
  """
  ✨ List `DateRange` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  dateRanges(
    """
    Filter condition to narrow down the query results.
    """
    where: DateRange_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DateRange_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DateRange_Having
  ): [DateRange!]! @fdc_generated(from: "DateRange", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Dimensions` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  dimensionss(
    """
    Filter condition to narrow down the query results.
    """
    where: Dimensions_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Dimensions_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Dimensions_Having
  ): [Dimensions!]! @fdc_generated(from: "Dimensions", purpose: QUERY_MULTIPLE)
  """
  ✨ List `DrugInteraction` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  drugInteractions(
    """
    Filter condition to narrow down the query results.
    """
    where: DrugInteraction_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DrugInteraction_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DrugInteraction_Having
  ): [DrugInteraction!]! @fdc_generated(from: "DrugInteraction", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Employee` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  employees(
    """
    Filter condition to narrow down the query results.
    """
    where: Employee_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Employee_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Employee_Having
  ): [Employee!]! @fdc_generated(from: "Employee", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ExpiryWarningThresholds` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  expiryWarningThresholdss(
    """
    Filter condition to narrow down the query results.
    """
    where: ExpiryWarningThresholds_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ExpiryWarningThresholds_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ExpiryWarningThresholds_Having
  ): [ExpiryWarningThresholds!]! @fdc_generated(from: "ExpiryWarningThresholds", purpose: QUERY_MULTIPLE)
  """
  ✨ List `FinancialRecord` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  financialRecords(
    """
    Filter condition to narrow down the query results.
    """
    where: FinancialRecord_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [FinancialRecord_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: FinancialRecord_Having
  ): [FinancialRecord!]! @fdc_generated(from: "FinancialRecord", purpose: QUERY_MULTIPLE)
  """
  ✨ List `FormularyStatus` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  formularyStatuses(
    """
    Filter condition to narrow down the query results.
    """
    where: FormularyStatus_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [FormularyStatus_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: FormularyStatus_Having
  ): [FormularyStatus!]! @fdc_generated(from: "FormularyStatus", purpose: QUERY_MULTIPLE)
  """
  ✨ List `GoodsReceipt` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  goodsReceipts(
    """
    Filter condition to narrow down the query results.
    """
    where: GoodsReceipt_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GoodsReceipt_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GoodsReceipt_Having
  ): [GoodsReceipt!]! @fdc_generated(from: "GoodsReceipt", purpose: QUERY_MULTIPLE)
  """
  ✨ List `InsuranceReimbursement` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  insuranceReimbursements(
    """
    Filter condition to narrow down the query results.
    """
    where: InsuranceReimbursement_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [InsuranceReimbursement_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: InsuranceReimbursement_Having
  ): [InsuranceReimbursement!]! @fdc_generated(from: "InsuranceReimbursement", purpose: QUERY_MULTIPLE)
  """
  ✨ List `InventoryLevel` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  inventoryLevels(
    """
    Filter condition to narrow down the query results.
    """
    where: InventoryLevel_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [InventoryLevel_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: InventoryLevel_Having
  ): [InventoryLevel!]! @fdc_generated(from: "InventoryLevel", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Invoice` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  invoices(
    """
    Filter condition to narrow down the query results.
    """
    where: Invoice_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Invoice_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Invoice_Having
  ): [Invoice!]! @fdc_generated(from: "Invoice", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Location` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  locations(
    """
    Filter condition to narrow down the query results.
    """
    where: Location_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Location_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Location_Having
  ): [Location!]! @fdc_generated(from: "Location", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Manufacturer` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  manufacturers(
    """
    Filter condition to narrow down the query results.
    """
    where: Manufacturer_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Manufacturer_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Manufacturer_Having
  ): [Manufacturer!]! @fdc_generated(from: "Manufacturer", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Message` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  messages(
    """
    Filter condition to narrow down the query results.
    """
    where: Message_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Message_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Message_Having
  ): [Message!]! @fdc_generated(from: "Message", purpose: QUERY_MULTIPLE)
  """
  ✨ List `MessageAttachment` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  messageAttachments(
    """
    Filter condition to narrow down the query results.
    """
    where: MessageAttachment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MessageAttachment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MessageAttachment_Having
  ): [MessageAttachment!]! @fdc_generated(from: "MessageAttachment", purpose: QUERY_MULTIPLE)
  """
  ✨ List `MessageReadReceipt` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  messageReadReceipts(
    """
    Filter condition to narrow down the query results.
    """
    where: MessageReadReceipt_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MessageReadReceipt_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MessageReadReceipt_Having
  ): [MessageReadReceipt!]! @fdc_generated(from: "MessageReadReceipt", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Payment` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  payments(
    """
    Filter condition to narrow down the query results.
    """
    where: Payment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Payment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Payment_Having
  ): [Payment!]! @fdc_generated(from: "Payment", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Payroll` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  payrolls(
    """
    Filter condition to narrow down the query results.
    """
    where: Payroll_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Payroll_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Payroll_Having
  ): [Payroll!]! @fdc_generated(from: "Payroll", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Product` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  products(
    """
    Filter condition to narrow down the query results.
    """
    where: Product_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Product_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Product_Having
  ): [Product!]! @fdc_generated(from: "Product", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ProductBatch` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  productBatches(
    """
    Filter condition to narrow down the query results.
    """
    where: ProductBatch_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ProductBatch_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ProductBatch_Having
  ): [ProductBatch!]! @fdc_generated(from: "ProductBatch", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ProductPricing` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  productPricings(
    """
    Filter condition to narrow down the query results.
    """
    where: ProductPricing_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ProductPricing_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ProductPricing_Having
  ): [ProductPricing!]! @fdc_generated(from: "ProductPricing", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ProductSupplier` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  productSuppliers(
    """
    Filter condition to narrow down the query results.
    """
    where: ProductSupplier_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ProductSupplier_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ProductSupplier_Having
  ): [ProductSupplier!]! @fdc_generated(from: "ProductSupplier", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PromotionalDiscount` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  promotionalDiscounts(
    """
    Filter condition to narrow down the query results.
    """
    where: PromotionalDiscount_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PromotionalDiscount_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PromotionalDiscount_Having
  ): [PromotionalDiscount!]! @fdc_generated(from: "PromotionalDiscount", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PurchaseOrder` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  purchaseOrders(
    """
    Filter condition to narrow down the query results.
    """
    where: PurchaseOrder_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PurchaseOrder_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PurchaseOrder_Having
  ): [PurchaseOrder!]! @fdc_generated(from: "PurchaseOrder", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PurchaseOrderLineItem` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  purchaseOrderLineItems(
    """
    Filter condition to narrow down the query results.
    """
    where: PurchaseOrderLineItem_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PurchaseOrderLineItem_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PurchaseOrderLineItem_Having
  ): [PurchaseOrderLineItem!]! @fdc_generated(from: "PurchaseOrderLineItem", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PurchaseRequisition` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  purchaseRequisitions(
    """
    Filter condition to narrow down the query results.
    """
    where: PurchaseRequisition_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PurchaseRequisition_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PurchaseRequisition_Having
  ): [PurchaseRequisition!]! @fdc_generated(from: "PurchaseRequisition", purpose: QUERY_MULTIPLE)
  """
  ✨ List `RecallDetails` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  recallDetailss(
    """
    Filter condition to narrow down the query results.
    """
    where: RecallDetails_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [RecallDetails_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: RecallDetails_Having
  ): [RecallDetails!]! @fdc_generated(from: "RecallDetails", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ReorderSuggestion` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  reorderSuggestions(
    """
    Filter condition to narrow down the query results.
    """
    where: ReorderSuggestion_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ReorderSuggestion_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ReorderSuggestion_Having
  ): [ReorderSuggestion!]! @fdc_generated(from: "ReorderSuggestion", purpose: QUERY_MULTIPLE)
  """
  ✨ List `SalesLineItem` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  salesLineItems(
    """
    Filter condition to narrow down the query results.
    """
    where: SalesLineItem_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [SalesLineItem_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: SalesLineItem_Having
  ): [SalesLineItem!]! @fdc_generated(from: "SalesLineItem", purpose: QUERY_MULTIPLE)
  """
  ✨ List `SalesTransaction` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  salesTransactions(
    """
    Filter condition to narrow down the query results.
    """
    where: SalesTransaction_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [SalesTransaction_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: SalesTransaction_Having
  ): [SalesTransaction!]! @fdc_generated(from: "SalesTransaction", purpose: QUERY_MULTIPLE)
  """
  ✨ List `SeasonalPattern` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  seasonalPatterns(
    """
    Filter condition to narrow down the query results.
    """
    where: SeasonalPattern_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [SeasonalPattern_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: SeasonalPattern_Having
  ): [SeasonalPattern!]! @fdc_generated(from: "SeasonalPattern", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Shift` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  shifts(
    """
    Filter condition to narrow down the query results.
    """
    where: Shift_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Shift_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Shift_Having
  ): [Shift!]! @fdc_generated(from: "Shift", purpose: QUERY_MULTIPLE)
  """
  ✨ List `StorageLocation` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  storageLocations(
    """
    Filter condition to narrow down the query results.
    """
    where: StorageLocation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [StorageLocation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: StorageLocation_Having
  ): [StorageLocation!]! @fdc_generated(from: "StorageLocation", purpose: QUERY_MULTIPLE)
  """
  ✨ List `SubstitutionRules` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  substitutionRuless(
    """
    Filter condition to narrow down the query results.
    """
    where: SubstitutionRules_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [SubstitutionRules_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: SubstitutionRules_Having
  ): [SubstitutionRules!]! @fdc_generated(from: "SubstitutionRules", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Supplier` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  suppliers(
    """
    Filter condition to narrow down the query results.
    """
    where: Supplier_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Supplier_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Supplier_Having
  ): [Supplier!]! @fdc_generated(from: "Supplier", purpose: QUERY_MULTIPLE)
  """
  ✨ List `SupplierPerformanceScore` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  supplierPerformanceScores(
    """
    Filter condition to narrow down the query results.
    """
    where: SupplierPerformanceScore_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [SupplierPerformanceScore_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: SupplierPerformanceScore_Having
  ): [SupplierPerformanceScore!]! @fdc_generated(from: "SupplierPerformanceScore", purpose: QUERY_MULTIPLE)
  """
  ✨ List `TemperatureRange` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  temperatureRanges(
    """
    Filter condition to narrow down the query results.
    """
    where: TemperatureRange_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TemperatureRange_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TemperatureRange_Having
  ): [TemperatureRange!]! @fdc_generated(from: "TemperatureRange", purpose: QUERY_MULTIPLE)
  """
  ✨ List `TemperatureReading` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  temperatureReadings(
    """
    Filter condition to narrow down the query results.
    """
    where: TemperatureReading_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TemperatureReading_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TemperatureReading_Having
  ): [TemperatureReading!]! @fdc_generated(from: "TemperatureReading", purpose: QUERY_MULTIPLE)
  """
  ✨ List `TherapeuticClass` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  therapeuticClasses(
    """
    Filter condition to narrow down the query results.
    """
    where: TherapeuticClass_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TherapeuticClass_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TherapeuticClass_Having
  ): [TherapeuticClass!]! @fdc_generated(from: "TherapeuticClass", purpose: QUERY_MULTIPLE)
  """
  ✨ List `TherapeuticSubclass` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  therapeuticSubclasses(
    """
    Filter condition to narrow down the query results.
    """
    where: TherapeuticSubclass_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TherapeuticSubclass_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TherapeuticSubclass_Having
  ): [TherapeuticSubclass!]! @fdc_generated(from: "TherapeuticSubclass", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
  """
  ✨ List `VolumeDiscount` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  volumeDiscounts(
    """
    Filter condition to narrow down the query results.
    """
    where: VolumeDiscount_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [VolumeDiscount_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: VolumeDiscount_Having
  ): [VolumeDiscount!]! @fdc_generated(from: "VolumeDiscount", purpose: QUERY_MULTIPLE)
}
