query VerifyProduct @auth(level: PUBLIC) {
  products(where: { genericName: { eq: "Paracetamol" } }) {
    id
    genericName
    brandName
    internalSKU
    manufacturer {
      name
    }
    business {
      name
    }
    category
    isActive
  }
}
